# Site settings
title: Seas' Personal Pages
email: seasleepy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for some things to live.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seasleepy.github.io" # the base hostname & protocol for your site
twitter_username: seasleepy
github_username:  seasleepy

# Build settings
markdown: kramdown
