name: seasleepy.github.io
url: http://seasleepy.github.io
description: A place for some words to live

permalink: /:year/:month/:day/:title/
paginate: 10
pygments: true

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
