# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Seas' Personal Pages
email: seasleepy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place for some things to live.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://seasleepy.github.io" # the base hostname & protocol for your site
twitter_username: seasleepy
github_username:  seasleepy

# Build settings
markdown: kramdown
